# Generated by Django 5.1.3 on 2024-12-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
    ]
